# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://xx:3306/wechat
    username: root
    password: xx
    driver-class-name: com.mysql.jdbc.Driver

wechat:
  official:
    token:
      key: officialTokenKey
      url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
      id: xx
      secret: xx
      expire_minute: 120